name: cadio-infra
description: Cadio AI CAD Platform - AWS infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
